site_name: LoyaltyDish

theme:
  name: material
  logo: null
  # favicon: images/logo.png
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"

extra_css:
  - css/extra.css

nav:
  - Get started: "get_started.md" # TODO
  - Create an account: "create_an_account.md"
  - Authentication: "authentication.md"
  - Obtain API keys: "authorization.md"
  - Rate limits & error handling: "rate_limits_and_error_handling.md"
  - API overview: "api_overview.md"
  - Customers: "customers.md"
  - Stores: "stores.md"
  - Store groups: "store_groups.md"
  - Campaigns: "campaigns.md"
  - Offers: "offers.md"
  - Segment: "segment.md"
  - Workflows: "workflows.md"
  - Email templating: "email_templing.md"
  - Notifications: "notifications.md"
  - 3rd party integrations: "" # TODO
  - Merchants: "merchants.md"
  - Roles & permissions: "roles_and_permissions.md"
  - Customer affinities: "customer_affinities.md"
  - POS:
      - Product: "pos/product.md"
      - Modifier: "pos/modifier.md"
      - Menu: ""
      - Order: ""
      - Order item: ""
      - Order status: ""
      - Checkout: "pos/checkout.md"
      - Discount: ""
      - Refund: "pos/refund.md"
      - Terminal: ""
      - Printer: ""
      - Floor plan: ""
  - Analytics: "analytics.md"

# TODO add the base object for each page
# TODO aff filters to queries

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
